version: '3'
services:
  rhyme-game-db:
    container_name: rhyme-game-db
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_DB=nakama
      - POSTGRES_PASSWORD=localdb
    volumes:
      - data:/var/lib/postgresql/data
    expose:
      - "8080"
      - "5432"
    ports:
      - "5432:5432"
      - "8080:8080"
  rhyme-game-nakama:
    container_name: rhyme-game-nakama
    image: heroiclabs/nakama:3.2.1
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
        /nakama/nakama migrate up --database.address postgres:localdb@rhyme-game-db:5432/nakama &&
        exec /nakama/nakama --name nakama1 --database.address postgres:localdb@rhyme-game-db:5432/nakama --logger.level DEBUG --session.token_expiry_sec 7200 --runtime.js_entrypoint "index.js" --match.max_empty_sec 30
    restart: always
    links:
      - "rhyme-game-db:db"
    depends_on:
      - rhyme-game-db
    volumes:
      - ./server/data:/nakama/data
    expose:
      - "7349"
      - "7350"
      - "7351"
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7350/"]
      interval: 10s
      timeout: 5s
      retries: 5
  rhyme-game-web:
    container_name: rhyme-game-web
    image: node:14
    user: "node"
    working_dir: /home/node/app
    depends_on:
      - rhyme-game-nakama
    volumes:
      - ./client:/home/node/app
    expose:
      - "3000"
      - "35729"
    ports:
      - "3000:3000"
    command: "yarn start"
volumes:
  data: